spring:
  application:
    name: zk-app-client
  cloud:
    zookeeper:
      discovery:
        root: /zk-service
      connect-string: localhost:2181
server:
  port: 8123

management:
  endpoints:
    web:
      #base-path: "/actuator"
      exposure:
        include: "*"